% template generator 
clearvars;
clc;
clear functions();
r = [...
reaction('Glucose.media (abcdef) -> Glucose.cell (abcdef)', 'id', 'Glucose_Import'),...
reaction('glycogen (abcdef) -> Glucose.cell (abcdef)', 'id', 'Unlabled_Glucose_Contribution'),...
reaction('Glucose.cell (abcdef) -> G6P (abcdef)', 'id', 'HK_Hexokinase'),...
reaction('G6P (abcdef) <-> F6P (abcdef)', 'id', 'PGUM_Phosphoglucomutase'),...
reaction('F6P (abcdef) <-> FBP (abcdef)', 'id', 'PFK_Phosphofructokinase'),...
reaction('FBP (abcdef) <-> 3PG (cba) + 3PG (def)', 'id', 'ALD_Aldolase-PGK_Phosphoglycerokinase'),...
reaction('DHAP (abc) <-> GA3P (abc)', 'id', 'TPI_Triosephosphate_Isomerase'),...
reaction('GA3P (abc) <-> 3PG (abc)', 'id', 'GA3PDH/PGK_Glyceraldehyde_3-Phosphate_Dehydrogenase-Phosphoglycerate_Kinase'),...
reaction('3PG (abc) <-> PEP (abc)', 'id', 'PGYM-ENOL_Phosphoglyceromutase-Enolase'),...
reaction('PEP (abc) -> Pyruvate (abc)', 'id', 'PK_Pyruvate_Kinase'),...
reaction('Pyruvate (abc) <-> Alanine (abc)', 'id', 'ALT_Alanine_Aminotransferase'),...
reaction('Pyruvate (abc) + 0.5*O2 <-> Lactate (abc)', 'id', 'LDH_Lactate_Dehydrogenase'),...
reaction('Lactate (abc) -> Lactate.media (abc)', 'id', 'Lactate_Export'),...
reaction('Pyruvate.media (abc) -> Pyruvate (abc)', 'id', 'Pyruvate_Import'),...
reaction('Pyruvate (abc) + CO2 (d) -> OAA (abcd)', 'id', 'PC_Pyruvate_Carboxylase'),...
reaction('OAA (abcd) <-> PEP (abc) + CO2 (d)', 'id', 'PEPCK_Phosphoenolpyruvate_Carboxykinase'),...
reaction('OAA.cell (abcd) -> Malate.cell (abcd)', 'id', 'MDH1_Malate_Dehydrogenase'),...
reaction('Pyruvate (abc) + 0.5*O2 -> AcCoA (bc) + CO2 (a)', 'id', 'PDH_Pyruvate_Dehydrogenase'),...
reaction('AcCoA (ef) + OAA (abcd) -> Citrate (dcbfea)', 'id', 'CS_Citrate_Synthase'),...
reaction('Citrate (abcdef) + 0.5*O2 -> a_ketoglutarate (abcde) + CO2 (f)', 'id', 'ACO-IDH_Aconitase-Isocitrate_Dehydrogenase'),...
reaction('Citrate (abcdef) + Malate.cell (ghij) -> Citrate.cell (abcdef) + Malate (ghij)', 'id', 'CIC_Mitochondrial_Citrate_Carrier'),...
reaction('a_ketoglutarate (abcde) + 0.5*O2 -> Succinate (bcde) + CO2 (a)', 'id', 'aKGDH-SCS_aKetoglutarate_Dehydrogenase-Succinyl_CoA_Synthase'),...
reaction('a_ketoglutarate (abcde) <-> Glutamate (abcde)', 'id', 'GDH_Glutamate_Dehydrogenase'),...
reaction('Glutamate (abcde) <-> Glutamine (abcde)', 'id', 'GS_Glutamine_Synthetase'),...
reaction('Glutamine.media (abcde) -> Glutamine (abcde)', 'id', 'Glutamine_Import'),...
reaction('a_ketoglutarate.cell (abcde) -> Glutamate (abcde)', 'id', 'Transaminase'),...
reaction('Succinate (abcd) + 0.5*O2 <-> Fumarate (abcd)', 'id', 'SDH_Succinate_Dehydrogenase'),...
reaction('Fumarate (abcd) <-> Malate (abcd)', 'id', 'FH_Fumarate_Hydratase'),...
reaction('Malate (abcd) + 0.5*O2 <-> OAA (abcd)', 'id', 'MDH2_Malate_Dehydrogenase'),...
reaction('Palmitoylcarnitine.media (abcdefghijklmnop) -> Palmitoylcarnitine (abcdefghijklmnop)', 'id', 'Fatty_Acid_Import'),...
reaction('Palmitoylcarnitine (abcdefghijklmnop) + 7*O2 -> AcCoA (ab) + AcCoA (cd) + AcCoA (ef) + AcCoA (gh) + AcCoA (ij) + AcCoA (kl) + AcCoA (mn) + AcCoA (op)', 'id', 'FAO_Fatty_Acid_Oxidation'),...
reaction('CO2.in (a) -> CO2 (a)', 'id', 'CO2_Import'),...
reaction('CO2 (a) -> CO2.out (a)', 'id', 'CO2_Export'),...
reaction('O2.in -> O2', 'id', 'O2_Import'),...
reaction('O2 -> O2.out', 'id', 'O2_Export'),...
reaction('G6P (abcdef) + O2 -> RB5P (bcdef) + CO2 (a)', 'id', 'G6PD_Glucose_6_Phosphate_Dehydrogenase-6PGD_6_Phosphogluconate_Dehydrogenase'),...
reaction('RB5P (abcde) <-> R5P (abcde)', 'id', 'R5PI_R5P_Isomerase'),...
reaction('RB5P (abcde) <-> XU5P (abcde)', 'id', 'R5P3E_R5P_3_Epimerase'),...
reaction('R5P (abcde) + XU5P (fghij) <-> GA3P (fgh) + S7P (abcdeij)', 'id', 'Transketolase_1'),...
reaction('GA3P (abc) + S7P (defghij) <-> E4P (defg) + F6P (abchij)', 'id', 'Transaldolase'),...
reaction('E4P (abcd) + XU5P (efghi) <-> GA3P (efg) + F6P (abcdhi)', 'id', 'Transketolase_2'),...
reaction('Glutamate (abcde) + Cysteine (fgh) -> Glutamylcysteine (abcdefgh)', 'id', 'GCS_yGlutamylcysteine_Synthetase'),...
reaction('Glutamylcysteine (abcdefgh) + Glycine (ij) -> Glutathione (abcdefghij)', 'id', 'GTS_Glutathione_Synthetase'),...
reaction('3PG (abc) -> Serine (abc)', 'id', 'PHGDH-PSP_3_Phosphoglycerate_Dehydrogenase-3-Phosphoserine_Phosphatase'),...
reaction('Serine (abc) <-> Glycine (ab) + CH2THF (c)', 'id', 'SHMT_Serine_Hydroxymethyltransferase'),...
reaction('CH2THF (a) <-> 510FTHF (a)', 'id', 'FAC_Folic_Acid_Cycle'),...
reaction('R5P (abcde) + Glycine (fg) -> GAR (abcdefg)', 'id', 'PPAT-GART1'),...
reaction('GAR (abcdefg) + 510FTHF (h) -> AIR (abcdefgh)', 'id', 'GART2-GART3'),...
reaction('AIR (abcdefgh) + HCO3 (i) <-> AICAR (abcdefghi)', 'id', 'PAICS1-ADSL'),...
reaction('AICAR (abcdefghi) + 510FTHF (j) -> AMP (abcdefghij)', 'id', 'ATIC1-ADSL'),...
reaction('Methionine.media (abcde) -> Methionine (abcde)', 'id', 'Methionine_Import'),...
reaction('Methionine (abcde) -> Homocysteine (abcd) + CH3 (e)', 'id', 'MT_Methyl_Transferase'),...
reaction('Homocysteine (abcd) + Serine (efg) -> Cystathione (abcdgfe)', 'id', 'CS_Cystathionine_Synthase'),...
reaction('Cystathione (abcdefg) -> Cysteine (gfe) + aKB (abcd)', 'id', 'CL_Cystathionine_Lyase'),...
reaction('CO2 (a) <-> HCO3 (a)', 'id', 'CA_Carbonic_Anhydrase'),...
reaction('Glycine.media (ab) -> Glycine (ab)', 'id', 'Glycine_Import'),...
reaction('Serine.media (abc) -> Serine (abc)', 'id', 'Serine_Import'),...
reaction('Cysteine.media (abc) -> Cysteine (abc)', 'id', 'Cysteine_Import'),...
reaction('DHAP (abc) + 0.5*O2 -> G3P (abc)', 'id', 'GPDH - Glycerol-3-phosphate Dehydrogenase'),...
reaction('Malate.cell (abcd) -> Pyruvate (abc) + CO2 (d)', 'id', 'ME_Malic_Enzyme'),...
reaction('ATP (abcdefghij) -> AMP (abcdefghij)', 'id', 'ATP Dephosphorylation'),...
reaction('Glutamate.media (abcde) -> Glutamate (abcde)', 'id', 'Glutamate Import'),...
]

% tracer block
% tracer data is same for all the experiments
t_common = tracer({...
'U-13C_Glucose: Glucose.media @ 1 2 3 4 5 6',...
});
t_common.frac = [1.0 ];
t_common.atoms.it(:,1) = [0.0,1.0];

% % define mass spectrometry measurements


% Read the CSV file
filename = "C:\Users\ghari\Documents\OPS\inca_wrapper\inca_custom\data_map\mat_format_fraction_data.csv"
data = readtable(filename);

% Display the first few rows of the table
disp(head(data));



% exp_0 = data(strcmp(data.exp_id, 'Cluster_706'), :);
% mean_str = exp_0(strcmp(exp_0.compound_name, 'AMP'), :).c_mean{1}(2:end-2);
% num_mean_array = str2double(strsplit(mean_str));

% std_str = exp_0(strcmp(exp_0.compound_name, 'AMP'), :).c_std{1}(2:end-2);
% num_std_array = str2double(strsplit(std_str));

arr_exps = unique(data.exp_id, 'stable');
arr_compounds = unique(data.compound_name, 'stable');

exp_objs = struct;
exp_objs.exps_lst = [];
for i = 1:size(arr_exps)
    disp("=====================")
    disp(i);
    exp_name = arr_exps{i};
    disp(exp_name);
    exp_related_data = data(strcmp(data.exp_id, exp_name), :);

    ms_exp_module = [...
        msdata('3PG: 3PG @ 1 2 3', 'more', 'H8O7P'),...
        msdata('AMP: AMP @ 1 2 3 4 5 6 7 8 9 10', 'more', 'H15N5O7P'),...
        msdata('E4P: E4P @ 1 2 3 4', 'more', 'H10O7P'),...
        msdata('FBP: FBP @ 1 2 3 4 5 6', 'more', 'H15O12P2'),...
        msdata('G6P: G6P @ 1 2 3 4 5 6', 'more', 'H14O9P'),...
        msdata('Glutamate: Glutamate @ 1 2 3 4 5', 'more', 'H10NO4'),...
        msdata('Glutamine: Glutamine @ 1 2 3 4 5', 'more', 'H11N2O3'),...
        msdata('Glutathione: Glutathione @ 1 2 3 4 5 6 7 8 9 10', 'more', 'H18N3O6S'),...
        msdata('Lactate: Lactate @ 1 2 3', 'more', 'H6O3'),...
        msdata('Malate: Malate @ 1 2 3 4', 'more', 'H7O5'),...
        msdata('PEP: PEP @ 1 2 3', 'more', 'H9O6P'),...
        msdata('Pyruvate: Pyruvate @ 1 2 3', 'more', 'H10O3'),...
        msdata('S7P: S7P @ 1 2 3 4 5 6 7', 'more', 'H16O10P'),...
        msdata('XU5P: XU5P @ 1 2 3 4 5', 'more', 'H12O8P'),...
        ];

    

    for j = 1:size(arr_compounds)
        % disp("++++++++++++++++++++++++++")
        % disp(j);
        compound_name = arr_compounds{j};
        compound_related_data = exp_related_data(strcmp(exp_related_data.compound_name, compound_name), :);
        mean_str = compound_related_data.c_mean{1}(2:end-2);
        num_mean_array = str2double(strsplit(mean_str));
        std_str = compound_related_data.c_std{1}(2:end-2);
        num_std_array = str2double(strsplit(std_str));

        num_mean_array = num_mean_array.';
        num_std_array = num_std_array.';

        ms_exp_module{compound_name}.idvs = idv([num_mean_array], 'id', {strcat('Cluster_one_', compound_name, '_0_0_1')}, 'std', [num_std_array], 'time', [0.0]);

    end
    
    
    exp_objs.exps_lst = [exp_objs.exps_lst,  experiment(t_common, 'id', exp_name , 'data_ms', ms_exp_module)];
    clear ms_exp_module;
end


m = model(r, 'expts', exp_objs.exps_lst);
filename = 'C:\Users\ghari\Documents\OPS\inca_wrapper\inca_custom\model_populated_dummy2.mat';
save(filename, 'm');

